spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wanghwtaiji/lambda-java8/
          search-paths: repo
          username: wanghwtaiji
          password: qwe456asd

server:
  port: 1201